server:
  port: 8072
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centerlized_db?createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


