server:
  port: 8072
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centerlized_db?createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    jpa:
      jpa:
        hibernate:
          ddl-auto: create-drop
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


